/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.edu.espe.Project_SPCS.GUI.model;

import ec.edu.espe.Project_SPCS.GUI.menu.MainDesktop;
import ec.edu.espe.STPCSProject.model.AgeDate;
import ec.edu.espe.STPCSProject.model.Date1;
import ec.edu.espe.STPCSProject.model.Employee;
import ec.edu.espe.STPCSProject.util.FileManager;
import ec.edu.espe.STPCSProject.util.FileSTPCS;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import static java.lang.String.format;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParsePosition;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Villarreal
 */
public class FRemploye extends javax.swing.JFrame {
    FileSTPCS file = new FileSTPCS();
    DefaultTableModel model = new DefaultTableModel();
    Employee employee=new Employee ();
      String []agregar= new String [7];
    String name;
    String id;
    String day;
    String month;
    String age;
    String datenacimiento;
    String dateadmision;
    String streetprincipal;
    String stretsecond;
    String city;
    
       
    

    /** Creates new form NewEmploye */
    public FRemploye() {
        initComponents();
      txtnew.setEnabled(false);
      txtnewwork.setEnabled(false);
    jbtnmodificar.setEnabled(false);
    jcboption.setEnabled(false);
           model.addColumn("Nombre");
        model.addColumn("Cedula");
        model.addColumn("Edad");
        model.addColumn("Ingreso");
        model.addColumn("Calle1");
        model.addColumn("Calle2");
        model.addColumn("Ciudad");
        this.tbldatos.setModel(model);
        
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtstretsecond = new javax.swing.JTextField();
        jlbid = new javax.swing.JLabel();
        btnañadir = new javax.swing.JButton();
        jlbname = new javax.swing.JLabel();
        jbtexit = new javax.swing.JButton();
        jlbdatenaciemiento = new javax.swing.JLabel();
        jLabelMobil = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabelPhones = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtstreetprincipal = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        jlbdateadmision = new javax.swing.JLabel();
        jLabelHomePhone1 = new javax.swing.JLabel();
        jcbcity = new javax.swing.JComboBox<>();
        jLabelMobil1 = new javax.swing.JLabel();
        jdcdateadmision = new com.toedter.calendar.JDateChooser();
        jdcdatenacimiento = new com.toedter.calendar.JDateChooser();
        btnhabilitrar = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatos = new javax.swing.JTable();
        btnsearch = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtstretsecond1 = new javax.swing.JTextField();
        txtsearch = new javax.swing.JTextField();
        lblingreso = new javax.swing.JLabel();
        btnlist = new javax.swing.JButton();
        pnlmodify = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnew = new javax.swing.JTextField();
        txtnewwork = new javax.swing.JTextField();
        jbtnmodificar = new javax.swing.JButton();
        jcboption = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblerror = new javax.swing.JLabel();
        lblerr = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtstretsecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstretsecondActionPerformed(evt);
            }
        });

        jlbid.setText("CÉDULA:");

        btnañadir.setText("AÑADIR");
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });

        jlbname.setText("NOMBRE:");

        jbtexit.setText("SALIR");
        jbtexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtexitActionPerformed(evt);
            }
        });

        jlbdatenaciemiento.setText("FECHA DE NACIMIENTO");

        jLabelMobil.setText("CALLE PRINCIPAL");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });

        jLabelPhones.setText("CALLE SECUNDARIA");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameKeyTyped(evt);
            }
        });

        txtstreetprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstreetprincipalActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("INGRESE LOS DATOS DEL EMPLEADO");

        jlbdateadmision.setText("FECHA DE ADMISION");

        jLabelHomePhone1.setText("CIUDAD:");

        jcbcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azuay, Cuenca", "Bolívar, Guaranda", "Cañar, Azogues", "Carchi, Tulcán", "Chimborazo, Riobamba", "Cotopaxi, Latacunga", "El Oro, Machala", "Esmeraldas, Esmeraldas", "Galápagos, Puerto Baquerizo Moreno", "Guayas, Guayaquil", "Imbabura, Ibarra", "Loja, Loja", "Los Ríos, Babahoyo", "Manabí, Portoviejo", "Morona Santiago, Macas", "Napo, Tena", "Orellana, Francisco de Orellana", "Pastaza, Puyo", "Pichincha, Quito", "Santa Elena, Santa Elena", "Santo Domingo de los Tsáchilas, Santo Domingo", "Sucumbíos, Nueva Loja", "Tungurahua, Ambato", "Zamora Chinchipe, Zamora" }));
        jcbcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbcityActionPerformed(evt);
            }
        });

        jLabelMobil1.setText("DIRECCIÓN");

        jdcdateadmision.setToolTipText("Selecicon o ingrese fecha en formato dd/mm/aa");
        jdcdateadmision.setDateFormatString("Selecicon o ingrese fecha en formato dd/mm/aa");

        jdcdatenacimiento.setToolTipText("Selecicon o ingrese fecha en formato dd/mm/aa");
        jdcdatenacimiento.setDateFormatString("Selecicon o ingrese fecha en formato dd/mm/aa");

        btnhabilitrar.setText("MODIFICAR");
        btnhabilitrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhabilitrarActionPerformed(evt);
            }
        });

        btnnew.setText("Limpiar");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        tbldatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldatos);

        btnsearch.setText("BUSCAR");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btndelete.setText("ELIMINAR");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        txtstretsecond1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstretsecond1ActionPerformed(evt);
            }
        });

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        lblingreso.setText("INGRESE CÉDULA PARA BUSCAR EMPLEADO");

        btnlist.setText("MOSTRAR LISTA");
        btnlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistActionPerformed(evt);
            }
        });

        pnlmodify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewActionPerformed(evt);
            }
        });

        jbtnmodificar.setText("ACTUALIZAR");
        jbtnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodificarActionPerformed(evt);
            }
        });

        jcboption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Nombre", "Cedula", "Edad" }));

        jLabel2.setText("Ingrese antiguo parametro");

        jLabel3.setText("Ingrese nuevo parametro");

        javax.swing.GroupLayout pnlmodifyLayout = new javax.swing.GroupLayout(pnlmodify);
        pnlmodify.setLayout(pnlmodifyLayout);
        pnlmodifyLayout.setHorizontalGroup(
            pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmodifyLayout.createSequentialGroup()
                .addGroup(pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlmodifyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlmodifyLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlmodifyLayout.createSequentialGroup()
                                .addComponent(jcboption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlmodifyLayout.createSequentialGroup()
                                .addGroup(pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnew, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnewwork, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(167, 167, 167))
            .addGroup(pnlmodifyLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jbtnmodificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmodifyLayout.setVerticalGroup(
            pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmodifyLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jcboption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnewwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jbtnmodificar)
                .addGap(23, 23, 23))
        );

        btnregresar.setText("REGRESAR");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtexit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnregresar)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnhabilitrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlmodify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btndelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnlist)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnsearch))
                                    .addComponent(lblingreso))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbdatenaciemiento)
                                    .addComponent(jlbdateadmision))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcdatenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcdateadmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jlbname))
                                    .addComponent(jlbid))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblerror, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblerr, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelMobil1)
                                .addGap(176, 176, 176))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPhones)
                                            .addComponent(jLabelMobil))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtstreetprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtstretsecond, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelHomePhone1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(btnnew)
                .addGap(125, 125, 125)
                .addComponent(btnañadir)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(791, Short.MAX_VALUE)
                    .addComponent(txtstretsecond1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(57, 57, 57)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbname))
                        .addGap(3, 3, 3)
                        .addComponent(lblerror)
                        .addGap(18, 18, 18)
                        .addComponent(lblerr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcdatenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbdatenaciemiento)))
                            .addComponent(jlbid)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMobil1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstreetprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMobil))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPhones)
                            .addComponent(txtstretsecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHomePhone1)
                            .addComponent(jcbcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbdateadmision)
                    .addComponent(jdcdateadmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btnañadir))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlmodify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhabilitrar))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblingreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearch))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlist)
                            .addComponent(btndelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtexit)
                    .addComponent(btnregresar))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addComponent(txtstretsecond1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(633, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstretsecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstretsecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstretsecondActionPerformed

    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed
    String aux="";
        name=txtname.getText();
        id=txtid.getText();
        day= Integer.toString(jdcdatenacimiento.getCalendar().get(Calendar.DAY_OF_MONTH));
        month= Integer.toString(jdcdatenacimiento.getCalendar().get(Calendar.MONTH)+1);
        age= Integer.toString(jdcdatenacimiento.getCalendar().get(Calendar.YEAR));
        int agetotal=file.Calculatedaño(Integer.parseInt(day), Integer.parseInt(month), Integer.parseInt(age));
        day= Integer.toString(jdcdateadmision.getCalendar().get(Calendar.DAY_OF_MONTH));
        month= Integer.toString(jdcdateadmision.getCalendar().get(Calendar.MONTH)+1);
        age= Integer.toString(jdcdateadmision.getCalendar().get(Calendar.YEAR));
        dateadmision=day+"-"+month+"-"+age;
        streetprincipal=txtstreetprincipal.getText();
        stretsecond=txtstretsecond.getText();
        city=(String)jcbcity.getSelectedItem();
        
        File archivo =new File("Employee.csv");
        aux = name+ ";" + id.toUpperCase() + ";" + Integer.toString(agetotal)+ ";" + dateadmision+ ";" + streetprincipal+ ";" + stretsecond +";"+city+"\n";
        FileManager.writeFile(archivo, aux);    
        JOptionPane.showMessageDialog(null,"Datos Guardados");       
            
        
    }//GEN-LAST:event_btnañadirActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtstreetprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstreetprincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstreetprincipalActionPerformed

    private void jcbcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbcityActionPerformed

    private void btnhabilitrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhabilitrarActionPerformed
        // TODO add your handling code here:
       
      txtnewwork.setEnabled(true);
      txtnew.setEnabled(true);
    jbtnmodificar.setEnabled(true);
    jcboption.setEnabled(true);
    jbtnmodificar.setEnabled(true);
    }//GEN-LAST:event_btnhabilitrarActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
    txtid.setText(" ");
    txtname.setText(" ");
    jdcdatenacimiento.resetKeyboardActions();
    jdcdateadmision.setDateFormatString(" ");
    txtstreetprincipal.setText(" ");
    txtstretsecond.setText(" ");
    jcbcity.getItemAt(1);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        FileSTPCS fiel =new FileSTPCS();  
        cleanTable();
        
        String route="Employee.csv";
    String data= fiel.searchDatas(route,txtsearch.getText());
    for(int i=0;i<=6;i++){
        agregar[i]=data.split(";")[i];
    }
    model.addRow(agregar);
     for(int i=0;i<=6;i++){
        agregar[i]="";
    }
    
    this.tbldatos.setModel(model);
  
                
    }//GEN-LAST:event_btnsearchActionPerformed
public void quitarFila(JTable tabla){
        try {
            model=(DefaultTableModel) tabla.getModel();
            model.removeRow(tabla.getSelectedRow());
            tabla.addRowSelectionInterval(0,0);
            model=null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione la fila que desea quitar.");
        }
    }
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       quitarFila(tbldatos);
    }//GEN-LAST:event_btndeleteActionPerformed
 
    private void cleanTable (){

DefaultTableModel tb = (DefaultTableModel) tbldatos.getModel();
        int a = tbldatos.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        }          
    }
    
    
    
    
    private void txtstretsecond1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstretsecond1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstretsecond1ActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
  
        
        
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jbtexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtexitActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jbtexitActionPerformed

    private void btnlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistActionPerformed
       this.tbldatos.setModel(employee.reportEmployee());
    }//GEN-LAST:event_btnlistActionPerformed

    private void txtnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewActionPerformed

    private void jbtnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodificarActionPerformed
        Employee employee = new Employee ();
        String newword=txtnew.getText();
        String change=txtnewwork.getText();
        
        if(jcboption.getSelectedItem()=="Nombre") {
            employee.modifyTable("Employee.csv", newword, 7,0, change);
        }
         if(jcboption.getSelectedItem()=="Cedula") {
             employee.modifyTable("Employee.csv", newword, 7,1,change);
        }
          if(jcboption.getSelectedItem()=="Ciudad") {
             employee.modifyTable("Employee.csv", newword, 7, 2, change);
        }
          this.tbldatos.setModel(employee.reportEmployee());
    }//GEN-LAST:event_jbtnmodificarActionPerformed

    private void txtnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyTyped
    keyTyped(evt);
    }//GEN-LAST:event_txtnameKeyTyped

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed

 

        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyPressed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
    MainDesktop main = new MainDesktop ();
    FRemploye em = new FRemploye ();
   
    main.setVisible(true);
    em.setVisible(false);
    em.disable();
// TODO add your handling code here:
    }//GEN-LAST:event_btnregresarActionPerformed
public static boolean isNumeric(String str)
{
    NumberFormat formatter = NumberFormat.getInstance();
    ParsePosition pos = new ParsePosition(0);
    formatter.parse(str, pos);
    return str.length() == pos.getIndex();
}
    
    public void keyTyped(KeyEvent e) { 
char c=e.getKeyChar(); 
if (!(Character.isLetter(c)||(c == KeyEvent.VK_BACK_SPACE)||(c == KeyEvent.VK_DELETE))){ 
getToolkit().beep(); 
e.consume(); 
} 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRemploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRemploye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnañadir;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhabilitrar;
    private javax.swing.JButton btnlist;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelHomePhone1;
    private javax.swing.JLabel jLabelMobil;
    private javax.swing.JLabel jLabelMobil1;
    private javax.swing.JLabel jLabelPhones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtexit;
    private javax.swing.JButton jbtnmodificar;
    private javax.swing.JComboBox<String> jcbcity;
    private javax.swing.JComboBox<String> jcboption;
    private com.toedter.calendar.JDateChooser jdcdateadmision;
    private com.toedter.calendar.JDateChooser jdcdatenacimiento;
    private javax.swing.JLabel jlbdateadmision;
    private javax.swing.JLabel jlbdatenaciemiento;
    private javax.swing.JLabel jlbid;
    private javax.swing.JLabel jlbname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblerr;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lblingreso;
    private javax.swing.JPanel pnlmodify;
    private javax.swing.JTable tbldatos;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnew;
    private javax.swing.JTextField txtnewwork;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtstreetprincipal;
    private javax.swing.JTextField txtstretsecond;
    private javax.swing.JTextField txtstretsecond1;
    // End of variables declaration//GEN-END:variables

}
