/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.Project_SPCS.GUI.model;

import ec.edu.espe.Project_SPCS.GUI.menu.MainDesktop;
import ec.edu.espe.STPCSProject.util.Operation;
import ec.edu.espe.STPCSProject.util.Validations;

/**
 *
 * @author José Andrés Zamora Miranda
 */
public class ModifyCustomerMainScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModifyCustomerMainScreen
     */
    public ModifyCustomerMainScreen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTittleCustomer = new javax.swing.JLabel();
        txtSearchIdentifyCard = new javax.swing.JTextField();
        btnButtonSearch = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar Cliente");

        lblTittleCustomer.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        lblTittleCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittleCustomer.setText("Ingrese la Cédula del Cliente");

        txtSearchIdentifyCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIdentifyCardActionPerformed(evt);
            }
        });
        txtSearchIdentifyCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchIdentifyCardKeyTyped(evt);
            }
        });

        btnButtonSearch.setText("Buscar");
        btnButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonSearchActionPerformed(evt);
            }
        });
        btnButtonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnButtonSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTittleCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchIdentifyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnButtonSearch)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTittleCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtSearchIdentifyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnButtonSearch)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchIdentifyCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIdentifyCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIdentifyCardActionPerformed

    private void btnButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonSearchActionPerformed
        ModifyCustomerResultScreen result = new ModifyCustomerResultScreen(txtSearchIdentifyCard.getText());
        Operation.mainResultAction(txtSearchIdentifyCard,result);
    }//GEN-LAST:event_btnButtonSearchActionPerformed

    private void btnButtonSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnButtonSearchKeyTyped
        boolean verificador = Validations.keyEnterPressed(evt);
        ModifyCustomerResultScreen result = new ModifyCustomerResultScreen(txtSearchIdentifyCard.getText());
        if (verificador == true) {
            Operation.mainResultAction(txtSearchIdentifyCard,result);
        } else {

        }
    }//GEN-LAST:event_btnButtonSearchKeyTyped

    private void txtSearchIdentifyCardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIdentifyCardKeyTyped
        Validations.verificationJustNumbers(txtSearchIdentifyCard);
    }//GEN-LAST:event_txtSearchIdentifyCardKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButtonSearch;
    private javax.swing.JLabel lblTittleCustomer;
    private javax.swing.JTextField txtSearchIdentifyCard;
    // End of variables declaration//GEN-END:variables
}
