/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.Project_SPCS.GUI.model;



import ec.edu.espe.STPCSProject.model.Provider;
import ec.edu.espe.STPCSProject.util.FileManager;
import ec.edu.espe.STPCSProject.util.Validations;
import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Dayanna Silva
 */
public class NewProvider1 extends javax.swing.JInternalFrame {

    private Provider person;
    private char validar;
    private String auxStringInput = null;
    private String auxStringForFile = null;
    private boolean RUCVerificationForSaving = false;
    private final Validations validation = new Validations();
    private int mouseClickCount = 0;    
    
    public NewProvider1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();
        lbllRUC = new javax.swing.JLabel();
        lblMobil = new javax.swing.JLabel();
        lblHomePhone = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhones = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtHomePhone = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Provedor");

        lblTitle.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("INGRESE LOS DATOS DEL PROVEDOR");

        lblName.setText("NOMBRE:");

        lblCompanyName.setText("EMPRESA:");

        lbllRUC.setText("CEDULA:");

        lblMobil.setText("CELULAR:");

        lblHomePhone.setText("CONVENCIONAL:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        lblPhones.setText("TELÉFONOS:");

        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });
        txtCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCompanyKeyTyped(evt);
            }
        });

        txtRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRUCActionPerformed(evt);
            }
        });
        txtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRUCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRUCKeyTyped(evt);
            }
        });

        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });

        txtHomePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomePhoneActionPerformed(evt);
            }
        });

        btnSearch.setText("GUARDAR");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnExit.setText("SALIR");

        jButton1.setText("LIMPIAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnSearch)
                                .addGap(39, 39, 39)
                                .addComponent(btnExit)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblCompanyName)
                                    .addComponent(lbllRUC))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(txtCompany)
                                    .addComponent(txtRUC))))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPhones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHomePhone)
                            .addComponent(lblMobil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHomePhone, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtMobile))
                        .addGap(92, 92, 92))))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompanyName)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllRUC)
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobil)
                    .addComponent(lblPhones)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomePhone)
                    .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnExit)
                    .addComponent(jButton1))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void txtRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRUCActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtHomePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomePhoneActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        person = new Provider();
         if (validation.checkOpenFile(new File("Provider.csv"))==false) {
            validationOfFullData();
            RUCVerificationForSaving = validation.IDVerification(txtRUC);
            if(RUCVerificationForSaving==true){
                person.setRuc(txtRUC.getText());
                if(txtName.getBackground() == Color.red||txtCompany.getBackground()==Color.red){
                    showMessageDialog(null, "Revise los parametros erroneos");
                }else{
                    person.setNameProvider(txtName.getText());
                    person.setNameCompany(txtCompany.getText());
                    if(txtHomePhone.getBackground()== Color.red||txtMobile.getBackground()==Color.red){
                        showMessageDialog(null, "Revise los parametros erroneos");
                    }else{
                        person.setPhoneNumber(txtHomePhone.getText());
                        person.setPhoneNumber2(txtMobile.getText());
                        auxStringForFile = toString();
                        //showMessageDialog(null, auxStringForFile);
                        String imput=txtName.getText()+";"+txtCompany.getText()+";"+
                                txtRUC.getText()+";"+txtMobile.getText()+";"+txtHomePhone.getText()+"\n";
                        FileManager.writeFile(new File("Provider.csv"), imput);
                        JOptionPane.showMessageDialog(this, "se ha agregado satisfactoriamente al archivo", 
                                "Agregado", JOptionPane.INFORMATION_MESSAGE);
                        cleanCells();
                    }
                }
            }else {
                showMessageDialog(null, "Revise los parametros erroneos");
            }     
         }else {
            showMessageDialog(null, "El archivo de datos se encuentra siendo usado por otra aplicación");
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    public void validationOfFullData(){
        if (txtCompany.getText().equals("")||txtHomePhone.getText().equals("")
                ||txtMobile.getText().equals("")||txtName.getText().equals("")||txtRUC.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Compos Vacios Verifique porfavor");   
            return;
        }
    }
    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        validar = evt.getKeyChar();
        validation.verificationJustLetters(validar,txtName);
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtCompanyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyKeyTyped
        validar = evt.getKeyChar();
        validation.verificationJustLetters(validar,txtCompany);
    }//GEN-LAST:event_txtCompanyKeyTyped

    private void txtRUCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyPressed
        person = new Provider();
       if(evt.getKeyCode() == 10)
       {
           validation.IDVerification(txtRUC);
       }
    }//GEN-LAST:event_txtRUCKeyPressed

    private void txtRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyTyped
        if (txtRUC.getText().length() <10) {
            validation.verificationJustNumbers(txtRUC);
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtRUCKeyTyped
     public void cleanCells()
    {
        txtName.setText("");
        txtRUC.setText("");
        txtCompany.setText("");
        txtHomePhone.setText("");
        txtMobile.setText("");
        mouseClickCount = 0;
    }
     public String toString()
    {
        auxStringInput = txtName.getText()+";"+txtCompany.getText()+";"+
                txtRUC.getText()+";"+txtMobile.getText()+";"+txtHomePhone.getText()+"\n";
        return auxStringInput;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProvider1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProvider1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProvider1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProvider1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProvider1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblHomePhone;
    private javax.swing.JLabel lblMobil;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhones;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbllRUC;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtHomePhone;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRUC;
    // End of variables declaration//GEN-END:variables
}
