/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.frameandclass.GUI;

import ec.edu.espe.model.Calculated;
import static ec.edu.espe.model.Calculated.TotalSalary;
import ec.edu.espe.model.FileManager;
import java.io.File;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Frame2 extends javax.swing.JFrame {
     FrameTable ven2 = new FrameTable();
     String name;
     float ies;
     float saldliquid;
        String totalsalary;
        String saldh;
        String numh;
        String acum="";

    
        FrameTable table = new FrameTable();
        String []agregar= new String [6];

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtname = new javax.swing.JTextField();
        txtshora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnumh = new javax.swing.JTextField();
        btncalculated = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Sueldo por hora: ");

        jLabel3.setText("Numero de horas: ");

        txtnumh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumhActionPerformed(evt);
            }
        });

        btncalculated.setText("Calcular");
        btncalculated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculatedActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingreso de datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btncalculated))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtshora)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel4)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtshora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnumh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(btncalculated)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumhActionPerformed
  public void sendDatas(){
              name=txtname.getText();
       saldh=txtshora.getText();
       numh=txtnumh.getText();
       
       saldliquid=TotalSalary(saldh,numh)-ies;
        
       totalsalary=String.valueOf(TotalSalary(saldh,numh));
           ies=(Float.parseFloat(totalsalary)*(9.45f))/100;
  
    ven2.lbl1.setText(txtname.getText());
    ven2.lbl2.setText(txtshora.getText());
    ven2.lbl3.setText(txtnumh.getText());
    ven2.lbl4.setText(totalsalary);
    ven2.lbl5.setText(String.valueOf(ies));
    ven2.lbl6.setText(String.valueOf(saldliquid));
 
    
  
    }
    
  
    
    private void btncalculatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculatedActionPerformed
      
        
        name=txtname.getText();
       saldh=txtshora.getText();
       numh=txtnumh.getText();
        
       totalsalary=String.valueOf(TotalSalary(saldh,numh));
           ies=(Float.parseFloat(totalsalary)*(9.45f))/100;
       saldliquid=TotalSalary(saldh,numh)-ies;
       acum = name+";"+saldh+";"+numh+"\n";
       Calculated calc = new Calculated();
       calc.calcular(acum);       
       agregar[0]=name;
       agregar[1]=saldh;
       agregar[2]=numh;
       agregar[3]=totalsalary;
       agregar[4]=String.valueOf(ies);
       agregar[5]=String.valueOf(saldliquid);
        table.llenarttable();
        table.model.addRow(agregar);    
      
 
       table.setVisible(true);
      sendDatas();     
  
       
    }//GEN-LAST:event_btncalculatedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalculated;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumh;
    private javax.swing.JTextField txtshora;
    // End of variables declaration//GEN-END:variables
}
